name: 'CI'
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v2
    - uses: akirak/elinter@v4
